/* Single source for every Academy course. `node tools/build-curriculum.js` splits it into:
 *   dist/academy-curriculum.js   (lessons, questions, labs — NO answers, shipped to the browser)
 *   api/_academy_answers.js      (answer keys only — graded on the server)
 * Unit: { t: title, body: lesson text, pts: [key points], q: { p: question, o: [options], a: correct index } }
 * Lab : { title, scenario, cols, rows (fictional data), tasks, deliverable } */
module.exports = {
  "DB-00": { outcome: "Work safely and confidently with devices, accounts, files and AI tools.",
    units: [
      { t: "Devices, accounts and staying safe", body: "Most incidents start with a reused password or a rushed click. A password manager gives every account a unique password, and multi-factor authentication (MFA) stops a stolen password from being enough. Treat unexpected links, attachments and urgent payment requests as suspicious until verified through a second channel.", pts: ["Unique password per account, stored in a password manager", "Turn on MFA for email first — it resets everything else"], q: { p: "Which single step best protects your other accounts if your email password leaks?", o: ["Using a longer nickname", "Enabling MFA on the email account", "Deleting old emails"], a: 1 } },
      { t: "Files, naming and structured data", body: "Good file habits save hours. Use a predictable name pattern (date first, then project, then version), keep one source of truth, and store tabular data with one header row, one record per row and one fact per column. Structured data can be sorted, filtered and validated; free-form notes cannot.", pts: ["Name files 2026-03-14_client-brief_v2", "One header row, one record per row, one fact per column"], q: { p: "Which file name is easiest to sort and find later?", o: ["final FINAL (2).docx", "2026-03-14_client-brief_v2.docx", "brief new.docx"], a: 1 } },
      { t: "Communicating and sharing responsibly", body: "Share the minimum needed with the fewest people, using view-only access by default. Before sending, check the recipient list, remove hidden data and confirm whether the content is confidential. Permissions should expire or be reviewed; 'anyone with the link' is rarely the right setting for business files.", pts: ["Default to view-only and named people", "Review who still has access after a project ends"], q: { p: "A document contains client pricing. What is the safest sharing setting?", o: ["Anyone with the link can edit", "Named colleagues, view-only", "Public on the web"], a: 1 } },
      { t: "AI literacy and mapping a workflow", body: "AI assistants draft, summarise and classify quickly, but can state wrong things confidently. Give them clear context, check important facts against a source, and never paste confidential data into a tool you are not approved to use. Map a workflow as trigger, steps, owner, output and exceptions before deciding what to automate.", pts: ["Verify AI output against a source before relying on it", "A workflow = trigger, steps, owner, output, exceptions"], q: { p: "What should you do before using an AI-written statistic in a client report?", o: ["Trust it — AI is usually right", "Check it against a reliable source", "Round it up"], a: 1 } }
    ],
    lab: { title: "Clean the messy inventory", scenario: "Nadia runs a small stationery shop. Her stock list was typed as free text. Turn it into a clean, structured table and note two safe-sharing decisions.", cols: ["Raw entry", "Note"], rows: [["A4 paper 500 sheets - 12 boxes - shelf B", "supplier: PaperCo"], ["blue pens (box of 50) 8", "reorder when < 3"], ["stapler heavy duty x4 shelf A", ""], ["Notebook A5 ruled 30pcs shelf B", "price 4.50"]], tasks: ["Create columns: item, unit, quantity, location, supplier/notes", "Rename the file using the naming pattern from Unit 2", "State who should see this file and with what access level"], deliverable: "A short write-up (or pasted table) showing your cleaned data, the new file name and your sharing choice." }
  },
  "DB-01": { outcome: "Turn a vague business problem into a validated, measurable recommendation.",
    units: [
      { t: "Stakeholder interviews", body: "An interview is for learning, not pitching. Ask about the last time the problem happened, what they did, and what it cost. Avoid leading questions such as 'wouldn't it be great if…'. Capture exact words and separate observation from interpretation.", pts: ["Ask about specific past events, not hypotheticals", "Record quotes; interpret afterwards"], q: { p: "Which is the best interview question?", o: ["Would you use an app that fixes this?", "Tell me about the last time an order was lost.", "Don't you think this is slow?"], a: 1 } },
      { t: "User journeys and problem validation", body: "Map the journey from trigger to outcome and mark where time, money or trust is lost. Validate the problem by checking that it is frequent, costly and currently worked around. A problem nobody pays to avoid is a weak foundation for a product.", pts: ["Mark pain points on the journey", "Validate: frequent, costly, already worked around"], q: { p: "Which evidence best validates a problem?", o: ["Everyone agreed it sounds useful", "People already spend time or money working around it", "A competitor exists"], a: 1 } },
      { t: "Measurable outcomes", body: "State the outcome as a number with a baseline and a target, for example 'reduce quote turnaround from 2 days to 4 hours'. Choose a metric the team can influence, and agree how and when it will be measured before building anything.", pts: ["Baseline, target, date", "Agree the measurement method upfront"], q: { p: "Which is a measurable outcome?", o: ["Make quoting better", "Cut quote turnaround from 2 days to 4 hours by June", "Improve customer happiness"], a: 1 } },
      { t: "Build, Reshape or Stop", body: "Weigh the validated problem, expected outcome, effort and risk. Build when value is clear and scope is small. Reshape when the problem is real but the proposed solution is wrong. Stop when the problem is rare, cheap or unowned. A clear Stop is a successful discovery result.", pts: ["Three honest options, not one", "Stopping early saves the budget"], q: { p: "The problem is real but the requested feature would not fix it. What is the recommendation?", o: ["Build it anyway", "Reshape the solution", "Stop the project without explanation"], a: 1 } }
    ],
    lab: { title: "Recommend for Al Noor Trading", scenario: "Al Noor Trading loses quotes because requests arrive by WhatsApp, email and phone. Use the interview notes to write a Build / Reshape / Stop recommendation.", cols: ["Interviewee", "Quote"], rows: [["Sales lead", "I re-type the same quote three times"], ["Owner", "We lost two deals last month, both slow replies"], ["Accountant", "I chase sales for figures every Friday"], ["Customer (call)", "I asked on WhatsApp and never heard back"]], tasks: ["List the top two pain points with evidence", "Write one measurable outcome with baseline and target", "Give your recommendation and one risk"], deliverable: "A half-page recommendation that cites at least two interview quotes." }
  },
  "DB-02": { outcome: "Design accessible interfaces and flows, from wireframe to interactive prototype.",
    units: [
      { t: "Information architecture and user flows", body: "Group content the way users think, not the way the organisation is structured. Draw the flow for one task from entry to completion, including the error and empty states. Keep primary navigation to a small, stable set of labels.", pts: ["Organise by user tasks", "Design error and empty states too"], q: { p: "What should a task flow include besides the happy path?", o: ["Nothing else", "Error and empty states", "Only marketing copy"], a: 1 } },
      { t: "Wireframes and layout", body: "Start low-fidelity so feedback focuses on structure, not colour. Establish hierarchy with size, spacing and alignment, and place the primary action where the eye finishes reading. Test the wireframe with one person before polishing.", pts: ["Low fidelity first", "One clear primary action per screen"], q: { p: "Why begin with low-fidelity wireframes?", o: ["They look nicer", "Feedback stays on structure rather than decoration", "They are required by law"], a: 1 } },
      { t: "Design systems and consistency", body: "A design system is a shared set of tokens (colour, type, spacing) and components. Reuse reduces bugs and speeds delivery. Name tokens by purpose, such as 'text-muted', not by value such as 'grey-500'.", pts: ["Tokens named by purpose", "Reuse components instead of redrawing"], q: { p: "Which token name ages best?", o: ["blue-500", "action-primary", "colour-3"], a: 1 } },
      { t: "Accessibility that ships", body: "Body text needs a contrast ratio of at least 4.5:1 against its background. Every control must work by keyboard with a visible focus ring, every input needs a programmatic label, and information must never rely on colour alone. Test with a screen reader before release.", pts: ["Contrast 4.5:1 for body text", "Keyboard, labels, focus — not colour alone"], q: { p: "What is the minimum contrast ratio for normal body text (WCAG AA)?", o: ["2:1", "4.5:1", "10:1"], a: 1 } }
    ],
    lab: { title: "Audit the booking form", scenario: "A clinic's booking form fails users. Review the audit table and write the fixes in priority order.", cols: ["Element", "Finding"], rows: [["Placeholder-only labels", "Screen reader announces 'edit text'"], ["Grey helper text #999 on white", "Contrast 2.8:1"], ["Submit button", "Not reachable by Tab"], ["Error message", "Red colour only, no text"]], tasks: ["Rank the four findings by user impact", "Give a concrete fix for each", "Say how you would re-test"], deliverable: "A prioritised fix list with one test method per fix." }
  },
  "DB-03": { outcome: "Build permission-aware web workflows with validated forms and clear errors.",
    units: [
      { t: "Forms and validation", body: "Validate on the client for speed and again on the server for safety, because the browser can be bypassed. Show errors next to the field in plain language, keep the user's input, and never clear a form after a failed submit.", pts: ["Client for convenience, server for truth", "Keep input after an error"], q: { p: "Why must validation also run on the server?", o: ["Servers are faster", "Client checks can be bypassed", "Browsers cannot validate"], a: 1 } },
      { t: "Displaying data", body: "Tables need sensible defaults: sorted by what matters, paginated, with a visible empty state and a loading state. Format dates, currency and numbers for the reader's locale, and never truncate data silently.", pts: ["Empty, loading and error states", "Locale-aware formatting"], q: { p: "What should a table show when there are no records?", o: ["A blank space", "A clear empty state explaining next steps", "An error alert"], a: 1 } },
      { t: "Navigation and error handling", body: "Users should always know where they are and how to go back. Handle failures gracefully: retry network errors, explain what happened, and never expose stack traces or internal identifiers. Log details for the team instead.", pts: ["Human error messages", "Log details privately"], q: { p: "What belongs in a user-facing error message?", o: ["A stack trace", "What happened and what to do next", "The database query"], a: 1 } },
      { t: "Permission-aware interfaces", body: "Hide controls a user cannot use for clarity, but remember that hiding is not security — the server must refuse the action. Design the interface from the user's role and show clear 'you do not have access' explanations when needed.", pts: ["Hiding a button is not authorisation", "The server decides"], q: { p: "A button is hidden for non-admins. Is the action secure?", o: ["Yes, they cannot click it", "Only if the server also checks the role", "Yes, if the URL is secret"], a: 1 } }
    ],
    lab: { title: "Harden the expense form", scenario: "Staff submit expense claims. Review the test log and design validation and permission rules.", cols: ["Test", "Result"], rows: [["Amount = -50", "Accepted"], ["Amount empty", "Form clears and shows nothing"], ["Employee opens /approve", "Page loads, buttons visible"], ["Receipt 25 MB", "Browser freezes"]], tasks: ["Write validation rules for each failed test", "Describe the error text for two of them", "State how approval permission is enforced"], deliverable: "A rule table plus the server-side permission check in plain language." }
  },
  "DB-04": { outcome: "Design records, authorisation, audit trails and API contracts that hold up in production.",
    units: [
      { t: "Records and schema design", body: "Model the nouns of the business as tables with a stable primary key, required fields, and relationships. Prefer explicit statuses over free text, store money as integer minor units, and record created and updated timestamps on every row.", pts: ["Stable IDs, explicit statuses", "Money as integer minor units"], q: { p: "How should money be stored to avoid rounding errors?", o: ["Floating-point numbers", "Integer minor units (cents)", "Text with a symbol"], a: 1 } },
      { t: "Authorisation on the server", body: "Authentication proves who you are; authorisation decides what you may do. Check ownership and role on every request, default to deny, and scope queries so users can only reach their own records.", pts: ["Default deny", "Check ownership on every request"], q: { p: "What is the safest default for an access rule?", o: ["Allow unless blocked", "Deny unless explicitly allowed", "Allow logged-in users"], a: 1 } },
      { t: "Audit trails and migrations", body: "An audit log records who did what and when, and is append-only. Change the schema through versioned migrations that can be reviewed and rolled back, never by editing production by hand.", pts: ["Append-only audit log", "Versioned, reversible migrations"], q: { p: "How should a production schema change be made?", o: ["Edit the live database by hand", "A reviewed, versioned migration", "Ask users to re-enter data"], a: 1 } },
      { t: "API contracts", body: "A contract states paths, methods, inputs, outputs and errors. Use correct status codes (201 created, 400 bad input, 401 unauthenticated, 403 forbidden, 404 missing, 409 conflict), make retried writes idempotent, and version breaking changes.", pts: ["Correct status codes", "Idempotent retries"], q: { p: "A signed-in user requests another user's invoice. Which status fits?", o: ["200", "403", "201"], a: 1 } }
    ],
    lab: { title: "Design the order API", scenario: "Design the records and endpoints for a small shop's orders using the sample rows.", cols: ["order_id", "customer", "status", "total"], rows: [["1001", "Layla", "paid", "1900"], ["1002", "Omar", "pending", "600"], ["1003", "Layla", "refunded", "900"], ["1004", "Sara", "paid", "300"]], tasks: ["Sketch the orders table with types", "Define POST /orders and GET /orders/:id with status codes", "State who may read an order"], deliverable: "A schema sketch and a short endpoint contract with authorisation rules." }
  },
  "DB-05": { outcome: "Use AI tools to build faster without giving up responsibility for the result.",
    units: [
      { t: "Writing precise task briefs", body: "A good brief states the goal, the files or context, the constraints, the acceptance checks and what not to change. Small, verifiable tasks beat one giant request. Ask for a plan first and review it before code is written.", pts: ["Goal, context, constraints, checks", "Small verifiable tasks"], q: { p: "Which element makes an AI task brief verifiable?", o: ["Acceptance checks", "Polite wording", "A long backstory"], a: 0 } },
      { t: "Inspecting diffs and running code", body: "Never merge output you have not read. Read the diff, run the code and tests, and look for changes outside the requested scope. Generated code that passes once may still hide deleted checks or invented APIs.", pts: ["Read every diff", "Run it — do not assume"], q: { p: "What is the minimum before accepting AI-generated code?", o: ["Read the diff and run the tests", "Check it compiles", "Ask the AI if it is correct"], a: 0 } },
      { t: "Debugging with AI", body: "Give the assistant the exact error, the smallest reproduction and what you already tried. Form a hypothesis, change one thing at a time and confirm the fix by reproducing the original failure first.", pts: ["Reproduce first", "One change at a time"], q: { p: "What should you do before asking AI to fix a bug?", o: ["Paste nothing", "Create a minimal reproduction and the exact error", "Rewrite the module"], a: 1 } },
      { t: "Dependencies and documenting AI contribution", body: "Verify that every suggested package exists, is maintained and is licensed appropriately — assistants sometimes invent names. Record where AI helped so reviewers know what to examine closely.", pts: ["Verify packages exist", "Disclose AI contribution"], q: { p: "An assistant suggests a package you have never heard of. What now?", o: ["Install it immediately", "Verify it exists, is maintained and licensed", "Ignore security"], a: 1 } }
    ],
    lab: { title: "Review the AI pull request", scenario: "An assistant produced a change to add discount codes. Review the change summary and decide what to accept.", cols: ["Change", "Observation"], rows: [["Added discountCode field", "Requested"], ["Removed email validation", "Not requested"], ["Imported 'easy-coupon-pro'", "Package not found on registry"], ["Tests", "2 new tests, 1 test deleted"]], tasks: ["List which changes you accept and which you reject", "Explain the risk of each unrequested change", "Write the disclosure note for the pull request"], deliverable: "A review comment set and a one-paragraph AI-contribution note." }
  },
  "DB-06": { outcome: "Deploy safely, watch what matters and respond to incidents calmly.",
    units: [
      { t: "Staging and safe deployment", body: "Staging mirrors production closely enough to catch mistakes. Deploy small changes often, keep a rollback path, and use environment variables for secrets — never commit them. Verify with a checklist after every release.", pts: ["Small, frequent releases", "Secrets in the environment"], q: { p: "Where should API secrets live?", o: ["In the repository", "In environment configuration", "In the page source"], a: 1 } },
      { t: "Monitoring and alerting", body: "Monitor what users feel: availability, error rate and latency. Alert on symptoms that need a human, with a clear owner and next step; noisy alerts get ignored.", pts: ["Watch errors, latency, availability", "Every alert has an owner"], q: { p: "What makes an alert useful?", o: ["It fires constantly", "It signals user impact and has an owner", "It is emailed to everyone"], a: 1 } },
      { t: "Defect response and incidents", body: "In an incident, stabilise first: communicate, mitigate, then investigate. Keep a timeline, assign one incident lead, and write a blameless review that produces concrete follow-up actions.", pts: ["Mitigate before root cause", "Blameless review with actions"], q: { p: "What comes first in a live incident?", o: ["Assign blame", "Mitigate impact and communicate", "Rewrite the system"], a: 1 } },
      { t: "Backup, restore and stating limits", body: "A backup that has never been restored is a hope, not a plan. Define how much data loss and downtime are acceptable, test restores on a schedule, and tell clients honestly what the system does not guarantee.", pts: ["Test restores regularly", "State limitations plainly"], q: { p: "When is a backup considered trustworthy?", o: ["When it exists", "After a successful test restore", "When it is large"], a: 1 } }
    ],
    lab: { title: "Triage the checkout outage", scenario: "Checkout errors spiked after a release. Use the timeline to write the incident summary.", cols: ["Time", "Event"], rows: [["10:02", "Release v42 deployed"], ["10:09", "Error rate rises from 1% to 22%"], ["10:12", "Support receives 6 complaints"], ["10:20", "Rollback to v41, errors return to 1%"]], tasks: ["Write the impact statement", "Give the most likely cause and how to confirm it", "List two follow-up actions"], deliverable: "A blameless incident summary of about 150 words." }
  },
  "DB-07": { outcome: "Scope, price, deliver and hand off client work professionally.",
    units: [
      { t: "Scope and estimating", body: "Write scope as outcomes, deliverables and explicit exclusions. Estimate in ranges, list assumptions, and add contingency for unknowns. A vague scope is the most common source of disputes.", pts: ["Scope includes exclusions", "Ranges and assumptions"], q: { p: "What protects both sides from scope disputes?", o: ["Verbal promises", "Written deliverables and exclusions", "A low price"], a: 1 } },
      { t: "Change-request discipline", body: "Anything outside the agreed scope is a change request: describe it, estimate impact on time and cost, and get written approval before starting. Saying yes without a change record is unpaid scope creep.", pts: ["Record, estimate, approve", "No silent extras"], q: { p: "A client asks for an extra feature mid-project. What first?", o: ["Build it quickly", "Log a change request with impact", "Refuse to talk"], a: 1 } },
      { t: "Handoff packaging", body: "A handoff lets someone else run the work: access list, how to deploy, how to back up, known issues, credentials transferred securely and a short training session. Verify the client can perform the key tasks unaided.", pts: ["Runbook + access list", "Client performs tasks unaided"], q: { p: "Which item belongs in a handoff pack?", o: ["Known issues and how to deploy", "Only the source files", "Your invoice history"], a: 0 } },
      { t: "Responsible marketing and support", body: "Describe results honestly: no guaranteed outcomes you cannot control and no testimonials without consent. Set support hours and response times in writing and keep a record of each request.", pts: ["No unprovable guarantees", "Written support terms"], q: { p: "Which claim is responsible?", o: ["Guaranteed #1 ranking", "Typical results and how we measured them", "Trusted by everyone"], a: 1 } }
    ],
    lab: { title: "Price the website project", scenario: "A restaurant wants a 5-page site with online booking. Use the notes to write scope, estimate and one change request.", cols: ["Item", "Detail"], rows: [["Pages", "Home, Menu, Booking, About, Contact"], ["Booking", "Calendar with email confirmation"], ["Content", "Client supplies text and photos"], ["Late request", "Add online ordering (not in brief)"]], tasks: ["Write scope with two exclusions", "Give a time and cost range with assumptions", "Draft the change request for online ordering"], deliverable: "A one-page scope and a change-request note." }
  },
  "DB-08": { outcome: "Demonstrate end-to-end capability on a fresh workflow, under time pressure, with a live defence.",
    units: [
      { t: "Readiness and the assessment contract", body: "The final challenge assesses independent capability on an unseen small-business workflow. Before you start you agree the contract: time window, permitted tools, what evidence you must submit and how it will be judged against a published rubric.", pts: ["Unseen workflow, fixed window", "Rubric is published in advance"], q: { p: "What does the assessment contract fix in advance?", o: ["The exact answer", "Time window, tools, evidence and rubric", "Nothing"], a: 1 } },
      { t: "The constrained build", body: "Work in the defined window from brief to a working, documented result. Prioritise a small complete solution over an ambitious unfinished one, and keep notes of decisions as you go — they become part of your evidence.", pts: ["Small and complete beats big and broken", "Log decisions while you work"], q: { p: "Which approach fits a timed build?", o: ["Start many features", "Deliver a small complete solution", "Wait for perfect information"], a: 1 } },
      { t: "Injected incidents", body: "Mid-challenge the assessor introduces a change request or a fault. This tests judgement: acknowledge, assess impact, decide, communicate and adapt without abandoning the work already done.", pts: ["Assess before reacting", "Communicate the trade-off"], q: { p: "A change request arrives mid-challenge. Best first response?", o: ["Ignore it", "Assess impact and state the trade-off", "Restart from scratch"], a: 1 } },
      { t: "Defence and verification", body: "You explain and defend your choices to an assessor. Independent verification is separate: a different qualified person checks your evidence and declares any conflict of interest. Passing completion is not the same as being verified.", pts: ["Defend with evidence", "Verifier must be independent"], q: { p: "Who may verify your work?", o: ["The person who reviewed and coached it", "An independent person with no conflict", "Anyone you choose"], a: 1 } }
    ],
    lab: { title: "Final challenge dossier", scenario: "Fictional SME 'BlueDune Cleaning' needs a job-booking workflow. Submit your challenge dossier summarising the brief, what you built, an injected change and your defence points.", cols: ["Requirement", "Detail"], rows: [["Customers", "Book a cleaning slot online"], ["Staff", "See only their assigned jobs"], ["Owner", "Sees all jobs and weekly totals"], ["Injected change", "Add a cancellation policy: free until 24h before"]], tasks: ["Summarise the solution and data model", "Explain how staff-only visibility is enforced", "Describe how you handled the injected change and one limitation"], deliverable: "A dossier of about 300 words ready for independent review." }
  },
  "PC-AD01": { outcome: "Run a professional office: calendar, inbox, meetings, controlled spreadsheets and confidentiality.",
    units: [
      { t: "Calendar and inbox control", body: "Protect focus time by scheduling blocks, and process email in batches with a simple rule: reply now if under two minutes, otherwise schedule it or delegate. Use folders or labels for action, waiting and reference.", pts: ["Batch the inbox", "Action / waiting / reference"], q: { p: "What is a good rule for quick emails?", o: ["Reply now if under two minutes", "Never reply", "Flag everything urgent"], a: 0 } },
      { t: "Meetings and minutes", body: "Every meeting has a purpose, an agenda and an owner. Minutes record decisions, actions with owners and due dates — not a transcript. Send them within 24 hours.", pts: ["Decisions and owned actions", "Send within 24 hours"], q: { p: "What must minutes record for each action?", o: ["The joke told", "Owner and due date", "Room number"], a: 1 } },
      { t: "Procurement and spreadsheet controls", body: "Protect spreadsheets with locked formulas, input validation and a change log. For purchases, separate who requests, who approves and who pays, and keep the quote, order and invoice together.", pts: ["Lock formulas, log changes", "Separate request, approval, payment"], q: { p: "Why separate requesting from approving a purchase?", o: ["It is slower", "Reduces error and fraud", "It is decorative"], a: 1 } },
      { t: "Confidential information and escalation", body: "Treat personal, financial and contract data as confidential: share on a need-to-know basis and store in approved locations. Escalate quickly when something is beyond your authority, stating facts, impact and what you need.", pts: ["Need-to-know only", "Escalate with facts and ask"], q: { p: "You receive a payment request that looks unusual. What now?", o: ["Pay quickly", "Verify through a second channel and escalate", "Forward to a friend"], a: 1 } }
    ],
    lab: { title: "Organise the week", scenario: "You support a manager. Turn the messy inputs into a plan, minutes and one escalation.", cols: ["Input", "Detail"], rows: [["Mon 10:00", "Supplier call (30 min)"], ["Tue", "Manager travelling, wants inbox summary"], ["Email", "Invoice from unknown vendor, urgent, new bank details"], ["Meeting notes", "Agreed: new laptops by 30th, Sara to get 3 quotes"]], tasks: ["Draft the weekly calendar with focus blocks", "Write the minutes with owner and date", "Write the escalation for the suspicious invoice"], deliverable: "A plan, minutes and a short escalation message." }
  },
  "PC-LG01": { outcome: "Follow a shipment from quote to reconciliation and handle exceptions.",
    units: [
      { t: "The shipment lifecycle", body: "A shipment moves through quote, booking, pickup, export clearance, transport, import clearance, delivery and invoicing. Each stage has an owner, a document and a milestone. Missing a milestone early delays every later step.", pts: ["Stage, owner, document, milestone", "Early misses cascade"], q: { p: "Which comes right after booking?", o: ["Invoicing", "Pickup", "Delivery"], a: 1 } },
      { t: "Shipping documents", body: "The commercial invoice states value and goods, the packing list details contents and weights, and the bill of lading is the transport contract and title document. Details must match across all three or customs may hold the cargo.", pts: ["Invoice, packing list, bill of lading", "Details must match"], q: { p: "Which document is the transport contract and evidence of receipt of goods?", o: ["Packing list", "Bill of lading", "Quote"], a: 1 } },
      { t: "Quotes and milestones", body: "A quote lists each charge, currency, validity and terms (such as who pays destination charges). Track milestones against the estimated dates and update the customer proactively when they move.", pts: ["Itemised, dated quotes", "Proactive milestone updates"], q: { p: "What should a freight quote always include?", o: ["Validity period and itemised charges", "A slogan", "Only a total"], a: 0 } },
      { t: "Exceptions and reconciliation", body: "When something goes wrong — damage, delay, wrong document — record it, notify the customer, act on the agreed procedure and note costs. At the end, reconcile quoted versus actual charges before invoicing.", pts: ["Record, notify, resolve", "Reconcile before invoicing"], q: { p: "Actual charges exceed the quote. What first?", o: ["Hide the difference", "Explain and get approval for the variance", "Cancel the shipment"], a: 1 } }
    ],
    lab: { title: "Fix the mismatched shipment", scenario: "A 12-carton shipment is held at customs. Compare the documents and prepare the fix and customer update.", cols: ["Document", "Cartons / weight"], rows: [["Commercial invoice", "12 cartons, 480 kg"], ["Packing list", "11 cartons, 455 kg"], ["Bill of lading", "12 cartons, 480 kg"], ["Quote", "USD 1,850 incl. origin charges"]], tasks: ["Identify the mismatch and the likely cause", "List the corrective steps and who does them", "Write the customer update"], deliverable: "A corrective action list and a customer update message." }
  },
  "PC-CS01": { outcome: "Resolve customer issues with clarity, empathy and clean records.",
    units: [
      { t: "Response handling", body: "Acknowledge fast, then resolve accurately. Restate the issue to confirm understanding, give a clear next step with a time, and follow up. A precise partial answer beats a vague complete one.", pts: ["Acknowledge, confirm, commit", "Follow up as promised"], q: { p: "What should a first reply include?", o: ["A clear next step and time", "An apology only", "A template with no detail"], a: 0 } },
      { t: "Complaint management", body: "Listen without interrupting, apologise for the experience, fix what you can and explain what you cannot. Offer options within policy and confirm the customer is satisfied before closing.", pts: ["Listen, apologise, fix, confirm", "Options within policy"], q: { p: "After resolving a complaint you should…", o: ["Close immediately", "Confirm the customer is satisfied", "Ignore the customer"], a: 1 } },
      { t: "Escalation", body: "Escalate when the issue is outside your authority, involves safety or legal risk, or has not been resolved in the agreed time. Hand over a summary so the customer never repeats their story.", pts: ["Clear triggers", "Hand over a summary"], q: { p: "What must an escalation include?", o: ["A summary of facts and actions taken", "Only the customer name", "A guess at blame"], a: 0 } },
      { t: "Tone and records", body: "Use plain, warm, professional language and avoid blame or jargon. Record each contact factually — what was asked, what was done, what is pending — so anyone can continue the case.", pts: ["Plain, warm, professional", "Factual case records"], q: { p: "Which record entry is best?", o: ["Customer angry, be careful", "Reported late order #482; refund offered; awaiting reply", "See email"], a: 1 } }
    ],
    lab: { title: "Handle the late delivery", scenario: "A customer's order is 6 days late and they are upset. Reply, log the case and decide on escalation.", cols: ["Field", "Detail"], rows: [["Order", "#482, promised 3 days, now day 9"], ["Customer message", "This is unacceptable, I need it for an event Friday"], ["Stock status", "Item shipped yesterday, tracking available"], ["Policy", "Delay > 5 days: refund shipping or 10% credit"]], tasks: ["Write the reply", "Write the case record", "Decide whether to escalate and why"], deliverable: "A reply message, a case note and your escalation decision." }
  },
  "PC-PR01": { outcome: "Source, evaluate and purchase with control and a clean paper trail.",
    units: [
      { t: "Sourcing and RFQs", body: "Define the requirement precisely before asking suppliers: specification, quantity, delivery date and evaluation criteria. Send the same RFQ to several suppliers so quotes can be compared fairly.", pts: ["Precise requirement", "Same RFQ to all suppliers"], q: { p: "Why send an identical RFQ to each supplier?", o: ["It looks professional", "So quotes can be compared fairly", "To confuse suppliers"], a: 1 } },
      { t: "Vendor evaluation", body: "Score suppliers on price, quality, delivery reliability, terms and risk with agreed weights. The cheapest quote is not always the lowest total cost once defects and delays are considered.", pts: ["Weighted scoring", "Consider total cost"], q: { p: "What is a better measure than the lowest price?", o: ["Total cost and reliability", "Supplier's size", "Alphabetical order"], a: 0 } },
      { t: "Purchase orders and three-way match", body: "A purchase order commits the company to specific terms. Before paying, match the PO, the goods receipt and the supplier invoice; only pay when quantity and price agree across all three.", pts: ["PO, receipt, invoice must agree", "Pay only after the match"], q: { p: "What are the three documents in a three-way match?", o: ["PO, goods receipt, supplier invoice", "Quote, email, contract", "Bank statement, PO, receipt"], a: 0 } },
      { t: "Contract basics", body: "Contracts record price, delivery, quality, payment terms, liability and how to end the agreement. Have anything unusual reviewed by the right authority before signing.", pts: ["Price, delivery, quality, payment, exit", "Unusual terms need review"], q: { p: "Who should review unusual contract terms?", o: ["The right authority (e.g. legal)", "Nobody", "The supplier only"], a: 0 } }
    ],
    lab: { title: "Choose the printer supplier", scenario: "Score three quotes for 20 office printers and run a three-way match on the delivery.", cols: ["Supplier", "Price / delivery / warranty"], rows: [["A", "USD 180 each, 5 days, 1 year"], ["B", "USD 165 each, 21 days, 6 months"], ["C", "USD 172 each, 7 days, 2 years"], ["Invoice check", "PO 20 units; received 18; invoiced 20"]], tasks: ["Score suppliers with weights you state", "Recommend one supplier", "Explain what to do about the invoice mismatch"], deliverable: "A scored comparison, a recommendation and a mismatch note." }
  },
  "PC-AC01": { outcome: "Support the accounting cycle accurately, from invoicing to month-end.",
    units: [
      { t: "Invoicing", body: "An invoice needs a unique number, date, seller and buyer details, itemised lines, tax where applicable, the total and payment terms. Issue promptly and record it in the ledger the same day.", pts: ["Unique number and clear terms", "Record the same day"], q: { p: "Which field must be unique on every invoice?", o: ["The invoice number", "The customer name", "The logo"], a: 0 } },
      { t: "Accounts payable", body: "Verify each supplier invoice against the order and receipt, code it to the right expense, get approval and pay by the due date. Late payment harms supplier relations; early payment wastes cash.", pts: ["Verify, code, approve, pay", "Pay on the due date"], q: { p: "What comes before paying a supplier invoice?", o: ["Verification and approval", "Nothing", "Archiving it"], a: 0 } },
      { t: "Reconciliation", body: "Reconciliation compares your records to an outside source, such as a bank statement, and explains every difference: timing items, errors or missing entries. An unexplained difference is a finding to investigate.", pts: ["Explain every difference", "Timing versus error"], q: { p: "A cheque you issued has not cleared. What kind of difference is this?", o: ["A timing difference", "Fraud", "A rounding error"], a: 0 } },
      { t: "Month-end and controls", body: "At month-end, cut off transactions, accrue known costs, reconcile key accounts and review for unusual movements. Controls such as approvals, segregation of duties and reviews prevent and detect mistakes.", pts: ["Cut-off, accruals, reconciliations", "Segregation of duties"], q: { p: "Which is a control?", o: ["Same person creates and approves payments", "A second person approves payments", "Trusting everyone"], a: 1 } }
    ],
    lab: { title: "Reconcile the bank account", scenario: "Reconcile the month's ledger to the bank statement and list the reconciling items.", cols: ["Line", "Amount (USD)"], rows: [["Ledger balance", "12,400"], ["Bank statement balance", "13,150"], ["Cheque #221 issued, not yet cleared", "-900"], ["Bank fee not yet in ledger", "-150"]], tasks: ["Show the reconciliation step by step", "Explain each reconciling item and the journal needed", "State whether any difference remains"], deliverable: "A reconciliation statement and the journal entry for the bank fee." }
  }
};
