// generated by tools/build-curriculum.js — server-only answer key
module.exports = {"DB-00":[1,1,1,1],"DB-01":[1,1,1,1],"DB-02":[1,1,1,1],"DB-03":[1,1,1,1],"DB-04":[1,1,1,1],"DB-05":[0,0,1,1],"DB-06":[1,1,1,1],"DB-07":[1,1,0,1],"DB-08":[1,1,1,1],"PC-AD01":[0,1,1,1],"PC-LG01":[1,1,0,1],"PC-CS01":[0,1,0,1],"PC-PR01":[1,0,0,0],"PC-AC01":[0,0,0,1]};
